Fix java.lang.BootstrapMethodError with some JVM's
See https://bugs.openjdk.org/browse/JDK-8269020

Erased generic argument type can cause exception with some JVM's:

```
exception is java.lang.BootstrapMethodError: bootstrap method initialization \
exception] with root cause

java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 1: \
class java.lang.Object is not convertible to interface org.geoserver.acl.domain.filter.Filter
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:279) ~[na:na]
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:328) ~[na:na]
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127) ~[na:na]
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:307) ~[na:na]
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:258) ~[na:na]
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:248) ~[na:na]
	at org.geoserver.acl.integration.jpa.repository.PredicateMapper.toPredicate(PredicateMapper.java:38) ~[classes/:na]
```